name: 🆕 功能建议
description: 提出一个想法！
title: 'feat: '
labels: [enhancement]
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: 🆒 你的使用场景
      description: 描述你的使用场景，以及这个功能会如何帮助你。
      placeholder: 当我做 [...] 时，我希望能够 [...]
  - type: textarea
    validations:
      required: true
    attributes:
      label: 🆕 你期望的方案
      description: 描述你希望发生什么。
  - type: textarea
    attributes:
      label: 🔍 你考虑过的替代方案
      description: 你是否考虑过其他解决方案或功能？
  - type: textarea
    attributes:
      label: ℹ️ 补充信息
      description: 还有其他你认为有帮助的上下文吗？
