name: 📚 文档
description: 我该如何……？
title: 'docs: '
labels: [documentation]
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: 📚 你的文档请求是否与某个问题相关？
      description: 清晰简洁地描述问题是什么。
      placeholder: 我觉得我应该能 [...]，但文档里看不出该怎么做。
  - type: textarea
    attributes:
      label: 🔍 你期望在哪里找到它？
      description: 你期望这段信息出现在文档的哪一页？
  - type: textarea
    attributes:
      label: ℹ️ 补充上下文
      description: 补充其他上下文或信息。
