name: 🆘 帮助
description: 我需要帮助……
title: 'help: '
labels: [help wanted]
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: 📚 你想做什么？
      description: 清晰简洁地描述你的目标。
      placeholder: 我不确定如何 [...]。
  - type: textarea
    attributes:
      label: 🔍 你已经尝试过什么？
      description: 你看过文档吗？试过不同方法吗？细节越多越好。
  - type: textarea
    attributes:
      label: ℹ️ 补充上下文
      description: 补充其他上下文或信息。
