contact_links:
  - name: 📖 文档
    url: https://nuxtseo.com
    about: 查看文档中的指南和示例。
  - name: 💬 Harlan 的 Discord 服务器
    url: https://discord.com/invite/5jDAMswWwX
    about: 加入友好的 Discord 服务器，获取问题帮助。
